version: "3.7"

services:
  elasticsearch:
    volumes:
      - type: bind
        source: ./data
        target: /usr/share/elasticsearch/data
    build:
      context: "./docker"
      dockerfile: "elasticsearch.Dockerfile"
    networks:
      - es_network
    ports:
        - 9200:9200
        - 9300:9300

  kibana:
    volumes:
      - type: bind
        source: ./docker/config/kibana.yml
        target: /usr/share/kibana/config/kibana.yml
    build:
      context: "./docker"
      dockerfile: "kibana.Dockerfile"
    networks:
      - es_network
    ports:
        - 5601:5601
    depends_on:
      - elasticsearch

  apm-server:
    volumes:
      - type: bind
        source: ./docker/config/apm-server.yml
        target: /usr/share/apm-server/apm-server.yml
    build:
      context: "./docker"
      dockerfile: "apm-server.Dockerfile"
    networks:
      - es_network
    ports:
        - 8200:8200
    depends_on:
      - elasticsearch

  heartbeat:
    build:
      context: "./docker"
      dockerfile: "heartbeat.Dockerfile"
    networks:
      - es_network
    depends_on:
      - elasticsearch
    restart: always

  app:
    volumes:
      - type: bind
        source: ./src
        target: /home/node/app
    build:
      context: ./docker
      dockerfile: app-node.Dockerfile
    container_name: node-server
    networks:
      - es_network
    ports:
      - 80:3000


networks:
  es_network:
    driver: bridge
