version: "3.7"

services:
  elasticsearch:
    volumes:
      - type: bind
        source: ./data
        target: /usr/share/elasticsearch/data
    build:
      context: "./docker"
      dockerfile: "elasticsearch.Dockerfile"
    networks:
      - es_network
    ports:
        - 9200:9200
        - 9300:9300

  kibana:
    build:
      context: "./docker"
      dockerfile: "kibana.Dockerfile"
    networks:
      - es_network
    ports:
        - 5601:5601
    depends_on:
      - elasticsearch

  apm-server:
    volumes:
      - type: bind
        source: ./apm-server.docker.yml
        target: /usr/share/apm-server/apm-server.yml
    build:
      context: "./docker"
      dockerfile: "apm-server.Dockerfile"
    networks:
      - es_network
    ports:
        - 8200:8200
    depends_on:
      - elasticsearch


networks:
  es_network:
    driver: bridge
